# Generated by Django 4.1.6 on 2023-04-29 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annoucements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='media/accoucements')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detailed_Marks_Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_roll_id', models.CharField(max_length=30)),
                ('student_document_pdf', models.FileField(upload_to='student_document')),
                ('student_program', models.CharField(max_length=100)),
                ('student_semester', models.CharField(max_length=100)),
                ('year_semester', models.DateTimeField()),
                ('type', models.CharField(max_length=30)),
                ('upload_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_roll_id', models.CharField(blank=True, max_length=30)),
                ('student_document_pdf', models.FileField(upload_to='student_document')),
                ('student_program', models.CharField(max_length=100)),
                ('student_semester', models.CharField(max_length=100)),
                ('year_semester', models.DateTimeField()),
                ('type', models.CharField(max_length=30)),
                ('upload_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='hot_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=2000)),
                ('link_event', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Result_Tabulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_roll_id', models.CharField(max_length=30)),
                ('student_document_pdf', models.FileField(upload_to='student_document')),
                ('student_program', models.CharField(max_length=100)),
                ('student_semester', models.CharField(max_length=100)),
                ('year_semester', models.DateTimeField()),
                ('type', models.CharField(max_length=30)),
                ('upload_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='student_profile',
            fields=[
                ('student_photo', models.ImageField(upload_to='student_photo')),
                ('student_name', models.CharField(max_length=200)),
                ('student_roll_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('college_name_student', models.CharField(max_length=500)),
                ('student_program', models.CharField(max_length=200)),
                ('student_admission_year', models.CharField(max_length=200)),
                ('student_semester', models.IntegerField()),
                ('student_father_name', models.CharField(max_length=200)),
                ('student_mother_name', models.CharField(max_length=200)),
                ('student_father_mobileno', models.IntegerField()),
                ('student_mobile_no', models.IntegerField()),
                ('student_email_id', models.EmailField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='student_progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_photo', models.ImageField(upload_to='student_result_photo')),
                ('student_name', models.CharField(max_length=200)),
                ('student_semester', models.IntegerField()),
                ('student_mobile_no', models.IntegerField()),
                ('student_mst1', models.IntegerField()),
                ('student_mst2', models.IntegerField()),
                ('student_mst3', models.IntegerField()),
                ('student_final_result', models.IntegerField()),
                ('student_id', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='question_paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=200)),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], default=0, max_length=200)),
                ('sub_pdf', models.FileField(blank=True, upload_to='questionpaper')),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science'), ('ME', 'Mechnical ')], max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student_enquiry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enq_date', models.DateTimeField(auto_now_add=True)),
                ('Enuery_descriptin', models.CharField(max_length=2000)),
                ('Query_related_to', models.CharField(max_length=2000)),
                ('college_reply', models.CharField(default='Pending', max_length=6000)),
                ('student_enquiry_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='answer_sheet_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], default=0, max_length=200)),
                ('subject_name', models.CharField(default=None, max_length=200)),
                ('sub_pdf', models.FileField(blank=True, upload_to='ansersheetstudent')),
                ('status', models.CharField(blank=True, default='Pending', max_length=200)),
                ('enq_date', models.DateTimeField(auto_now_add=True)),
                ('student_enquiry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
