# Generated by Django 4.1.6 on 2023-06-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_result_tabulation_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailed_marks_cards',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dmc',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hot_link',
            name='event_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
