# Generated by Django 4.1.6 on 2023-06-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_detailed_marks_cards_upload_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('collegeId', models.CharField(max_length=20)),
                ('mobileno', models.IntegerField(max_length=12)),
                ('photo', models.ImageField(upload_to='adminphoto')),
            ],
        ),
    ]
